spring.application.name=student-management
# Utiliser H2 (base de données en mémoire) pour les tests
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuration Hibernate pour H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Désactiver certaines fonctionnalités pour accélérer les tests
spring.jpa.open-in-view=false
spring.jmx.enabled=false

# Server port
server.port=8080

# Logging
logging.level.root=INFO
logging.level.tn.esprit=DEBUG